### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by gwern** [kosuke1701/ZACI-20-dataset#1]
The README could use some additional details:

1. Be more explicit about this being a face dataset; that's implied, but not really stated
2. What is the size of the images, and the size of the dataset itself?
3. Where does one download it? There only seem to be instructions on how to recreate it from Danboru2020 SFW.
2. It'd be good to include a selection of random samples
    
    3.  It'd also be good to include examples of errors in the zero-shot matching.
 3. Notebook instructions: in Tensorfork, some people have been trying the notebook with the various models, and the results seem to be worse than expected from your reported error rates. https://cdn.discordapp.com/attachments/735199480277631118/808037816743362651/unknown.png https://cdn.discordapp.com/attachments/735199480277631118/808041133514817566/unknown.png https://cdn.discordapp.com/attachments/702695448724373596/808056279573987348/107157137-7e990a80-6993-11eb-866f-4c4ff39ec5c0.png https://cdn.discordapp.com/attachments/702695448724373596/808053317598576650/c647a41c49df541525a523c11f6d46d9c7cb48c2.jpg -> https://cdn.discordapp.com/attachments/702695448724373596/808053447219085312/download.jpg

    Is there something missing from the notebooks or are these the results expected from those metrics? Are the models overfit?

**Comment by kosuke1701** [comment]
Thanks for the suggestions! I updated README.md to improve documentations.

> Where does one download it? There only seem to be instructions on how to recreate it from Danboru2020 SFW.

I couldn't provide download links because the size of the dataset is too large (~17GB) to upload to my Google drive or a github release. Do you have any suggestion for this issue?

> the results seem to be worse than expected from your reported error rates

Since negative pairs in the test set is randomly selected and contain many easy negatives (image pair of completely different characters), the reported performance over-estimates models' performance in some sense. I'm creating more hard test data with adversarially sampled negative pairs to report more realistic error rates.

**Comment by gwern** [comment]
> I couldn't provide download links because the size of the dataset is too large (~17GB) to upload to my Google drive or a github release. Do you have any suggestion for this issue?

17GB is pretty small. I can host that on my rsync server for you if you can provide anywhere I can download it. (If you have nowhere you can put that temporarily, I can also temporarily give you SSH access to rsync/scp it up. Email me your SSH public key.)

**Comment by kosuke1701** [comment]
Thank you for your generous offer! I sent temporal links to download the dataset via e-mail.

**Comment by gwern** [comment]
It should now be downloadable as:

```.Bash
rsync --verbose rsync://78.46.86.149:873/biggan/20210206-kosukeakimoto-zaci2020-danbooru2020zeroshotfaces.tar ./
```

---

A comparison with https://github.com/arkel23/animesion would also be good.

**Comment by kosuke1701** [comment]
Thank you very much! I'll update readme with the new rsync link.
